CREATE TABLE products (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          price DOUBLE NOT NULL,
                          image_url VARCHAR(255),
                          in_stock BOOLEAN NOT NULL
);

INSERT INTO products (name, price, image_url, in_stock) VALUES
                                                            ('Laptop Model A1', 1100.00, 'https://example.com/laptop1.jpg', true),
                                                            ('Laptop Model A2', 1050.00, 'https://example.com/laptop2.jpg', true),
                                                            ('Laptop Model A3', 1150.00, 'https://example.com/laptop3.jpg', true),
                                                            ('Laptop Model A4', 1200.00, 'https://example.com/laptop4.jpg', true),
                                                            ('Laptop Model A5', 1250.00, 'https://example.com/laptop5.jpg', true),
                                                            ('Desktop Model B1', 1500.00, 'https://example.com/desktop1.jpg', true),
                                                            ('Desktop Model B2', 1600.00, 'https://example.com/desktop2.jpg', true),
                                                            ('Desktop Model B3', 1550.00, 'https://example.com/desktop3.jpg', true),
                                                            ('Desktop Model B4', 1450.00, 'https://example.com/desktop4.jpg', true),
                                                            ('Desktop Model B5', 1400.00, 'https://example.com/desktop5.jpg', true),
                                                            ('Tablet Model C1', 700.00, 'https://example.com/tablet1.jpg', true),
                                                            ('Tablet Model C2', 750.00, 'https://example.com/tablet2.jpg', true),
                                                            ('Tablet Model C3', 800.00, 'https://example.com/tablet3.jpg', true),
                                                            ('Tablet Model C4', 780.00, 'https://example.com/tablet4.jpg', true),
                                                            ('Tablet Model C5', 820.00, 'https://example.com/tablet5.jpg', true),
                                                            ('Smartphone Model D1', 600.00, 'https://example.com/smartphone1.jpg', true),
                                                            ('Smartphone Model D2', 650.00, 'https://example.com/smartphone2.jpg', true),
                                                            ('Smartphone Model D3', 700.00, 'https://example.com/smartphone3.jpg', true),
                                                            ('Smartphone Model D4', 680.00, 'https://example.com/smartphone4.jpg', true),
                                                            ('Smartphone Model D5', 720.00, 'https://example.com/smartphone5.jpg', true),
                                                            ('Camera Model E1', 850.00, 'https://example.com/camera1.jpg', true),
                                                            ('Camera Model E2', 900.00, 'https://example.com/camera2.jpg', true),
                                                            ('Camera Model E3', 950.00, 'https://example.com/camera3.jpg', true),
                                                            ('Camera Model E4', 880.00, 'https://example.com/camera4.jpg', true),
                                                            ('Camera Model E5', 920.00, 'https://example.com/camera5.jpg', true),
                                                            ('Headphones Model F1', 120.00, 'https://example.com/headphones1.jpg', true),
                                                            ('Headphones Model F2', 130.00, 'https://example.com/headphones2.jpg', true),
                                                            ('Headphones Model F3', 110.00, 'https://example.com/headphones3.jpg', true),
                                                            ('Headphones Model F4', 140.00, 'https://example.com/headphones4.jpg', true),
                                                            ('Headphones Model F5', 125.00, 'https://example.com/headphones5.jpg', true),
                                                            ('Keyboard Model G1', 80.00, 'https://example.com/keyboard1.jpg', true),
                                                            ('Keyboard Model G2', 85.00, 'https://example.com/keyboard2.jpg', true),
                                                            ('Keyboard Model G3', 90.00, 'https://example.com/keyboard3.jpg', true),
                                                            ('Keyboard Model G4', 95.00, 'https://example.com/keyboard4.jpg', true),
                                                            ('Keyboard Model G5', 100.00, 'https://example.com/keyboard5.jpg', true),
                                                            ('Monitor Model H1', 350.00, 'https://example.com/monitor1.jpg', true),
                                                            ('Monitor Model H2', 360.00, 'https://example.com/monitor2.jpg', true),
                                                            ('Monitor Model H3', 370.00, 'https://example.com/monitor3.jpg', true),
                                                            ('Monitor Model H4', 380.00, 'https://example.com/monitor4.jpg', true),
                                                            ('Monitor Model H5', 390.00, 'https://example.com/monitor5.jpg', true),
                                                            ('Printer Model I1', 250.00, 'https://example.com/printer1.jpg', true),
                                                            ('Printer Model I2', 260.00, 'https://example.com/printer2.jpg', true),
                                                            ('Printer Model I3', 270.00, 'https://example.com/printer3.jpg', true),
                                                            ('Printer Model I4', 280.00, 'https://example.com/printer4.jpg', true),
                                                            ('Printer Model I5', 290.00, 'https://example.com/printer5.jpg', true),
                                                            ('Router Model J1', 120.00, 'https://example.com/router1.jpg', true),
                                                            ('Router Model J2', 125.00, 'https://example.com/router2.jpg', true),
                                                            ('Router Model J3', 130.00, 'https://example.com/router3.jpg', true),
                                                            ('Router Model J4', 135.00, 'https://example.com/router4.jpg', true),
                                                            ('Router Model J5', 140.00, 'https://example.com/router5.jpg', true),
                                                            ('Speaker Model K1', 180.00, 'https://example.com/speaker1.jpg', true),
                                                            ('Speaker Model K2', 185.00, 'https://example.com/speaker2.jpg', true),
                                                            ('Speaker Model K3', 190.00, 'https://example.com/speaker3.jpg', true),
                                                            ('Speaker Model K4', 195.00, 'https://example.com/speaker4.jpg', true),
                                                            ('Speaker Model K5', 200.00, 'https://example.com/speaker5.jpg', true),
                                                            ('Mouse Model L1', 30.00, 'https://example.com/mouse1.jpg', true),
                                                            ('Mouse Model L2', 35.00, 'https://example.com/mouse2.jpg', true),
                                                            ('Mouse Model L3', 40.00, 'https://example.com/mouse3.jpg', true),
                                                            ('Mouse Model L4', 45.00, 'https://example.com/mouse4.jpg', true),
                                                            ('Mouse Model L5', 50.00, 'https://example.com/mouse5.jpg', true);
